# Guess the output of each answer before you click RUN
# Try to write down your answer before and see how you do... keep it mind I made it a little tricky for you :)
# Each print statement is the next step in solving the problem
print ('----------------------------')
print((5 + 4) * 10 / 2)
print(9 * 10 / 2)
print(9 * 5)
print ('45')
print ('----------------------------')
print(((5 + 4) * 10) / 2)
print((9 * 10) / 2)
print(90 / 2) 
print('45')
print ('----------------------------')
print((5 + 4) * (10 / 2))
print(9 * 5) 
print ('45')
print ('----------------------------')
print(5 + (4 * 10) / 2)
print(5 + 40 / 2)
print(5 + 20)
print ('25')
print ('----------------------------')
print(5 + 4 * 10 // 2)
print(5 + 4 * 5)
print(5 + 20)
print ('25')